name: 🎉 Deploy Website to BigRock

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🚚 Deploy via FTP
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Get latest code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: 📂 Sync files to BigRock
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ./
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          website_deploy.zip
          README.md
          update_footers.py
          update_navigation.py
